In [6]:
import numpy as np

# Membuat matriks 6x6 dengan angka acak antara 0 hingga 15
citra_awal = np.array([[10,  9, 15,  8,  5,  4],
 [ 2,  5,  6,  0, 12,  1],
 [ 1,  5,  5, 12, 14,  1],
 [ 6, 11,  3,  4, 14,  3],
 [ 8,  0, 14,  2, 11,  7],
 [ 3,  8,  3,  5,  6,  0]]
)

# Menampilkan citra awal sebelum penskalaan
print("Citra Awal:")
print(citra_awal)
print()

# Faktor skala untuk penskalaan kecil
s_x = 1.5
s_y = 1.5

# Menghitung dimensi citra hasil penskalaan
new_width = int(citra_awal.shape[1] * s_x)
new_height = int(citra_awal.shape[0] * s_y)

# Inisialisasi matriks untuk citra hasil penskalaan
citra_hasil = np.zeros((new_height, new_width), dtype=citra_awal.dtype)

# Melakukan penskalaan citra kecil
for i in range(new_height):
    for j in range(new_width):
        citra_hasil[i, j] = citra_awal[int(i/s_y), int(j/s_x)]

# Menampilkan citra hasil penskalaan
print("Citra Hasil Penskalaan:")
print(citra_hasil)


Citra Awal:
[[10  9 15  8  5  4]
 [ 2  5  6  0 12  1]
 [ 1  5  5 12 14  1]
 [ 6 11  3  4 14  3]
 [ 8  0 14  2 11  7]
 [ 3  8  3  5  6  0]]

Citra Hasil Penskalaan:
[[10 10  9 15 15  8  5  5  4]
 [10 10  9 15 15  8  5  5  4]
 [ 2  2  5  6  6  0 12 12  1]
 [ 1  1  5  5  5 12 14 14  1]
 [ 1  1  5  5  5 12 14 14  1]
 [ 6  6 11  3  3  4 14 14  3]
 [ 8  8  0 14 14  2 11 11  7]
 [ 8  8  0 14 14  2 11 11  7]
 [ 3  3  8  3  3  5  6  6  0]]
