In [1]:
import numpy as np

# Ukuran citra
rows = 6  # jumlah baris
cols = 6  # jumlah kolom

# Matriks citra asli A
A = np.array([[10,  9, 15,  8,  5,  4],
 [ 2,  5,  6,  0, 12,  1],
 [ 1,  5,  5, 12, 14,  1],
 [ 6, 11,  3,  4, 14,  3],
 [ 8,  0, 14,  2, 11,  7],
 [ 3,  8,  3,  5,  6,  0]]
)

# Matriks untuk citra hasil translasi B
B = np.zeros((rows, cols), dtype=int)

# Vektor translasi
x = 2  # translasi horizontal
y = 1  # translasi vertikal

# Proses translasi
for i in range(rows):
    for j in range(cols):
        new_x = j + x
        new_y = i + y
        if 0 <= new_x < cols and 0 <= new_y < rows:
            B[new_y][new_x] = A[i][j]

print("Citra asli A:")
print(A)
print("\nCitra hasil translasi B:")
print(B)


Citra asli A:
[[10  9 15  8  5  4]
 [ 2  5  6  0 12  1]
 [ 1  5  5 12 14  1]
 [ 6 11  3  4 14  3]
 [ 8  0 14  2 11  7]
 [ 3  8  3  5  6  0]]

Citra hasil translasi B:
[[ 0  0  0  0  0  0]
 [ 0  0 10  9 15  8]
 [ 0  0  2  5  6  0]
 [ 0  0  1  5  5 12]
 [ 0  0  6 11  3  4]
 [ 0  0  8  0 14  2]]
